## **What is Numpy ?**
NumPy is the fundamental package for scientific computing in Python. It is a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete fourier transfroms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulation n-dimensional arrays of homogenous data types.

### **Numpy Arrays Vs Python Sequences**
*  NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of ndarray will create a new array and delete the original.
*  The elements in a NumPy arrays are all required to be of the same data types, and thus will be the same size in memory.
*  NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python's built-in sequence.
*  A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; through these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

# **1. Creating Numpy Arrays**

In [ ]:
import numpy as np     # np.array

In [ ]:
A = np.array([1,2,3,4,5])
print(A)
print(type(A))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# 2D Array

B = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(B)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
# 3D Array

C = np.array([[[1,2],[3,4]],[[5,6],[7,9]]])
print(C)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 9]]]


In [ ]:
# Different Datatypes

f = np.array([1,2,3],dtype=float)
print(f)

b = np.array([1,False,2],dtype=bool)
print(b)

[1. 2. 3.]
[ True False  True]


In [ ]:
# Range Function

a = np.arange(1,11)
print(a)

s = np.arange(1,11,2)
print(s)

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [ ]:
# Reshape Function

a = np.arange(1,11).reshape(2,5)
print(a)
print('\n')
b = np.arange(1,21).reshape(5,2,2)
print(b)
print('\n')
c = np.arange(1,25).reshape(4,3,2)
print(c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]

 [[17 18]
  [19 20]]]


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]]


In [ ]:
# Ones and Zeros            # It used where you want to initialize the array or matrices faster

a = np.ones((4,2))
print(a)
print('\n')
b = np.zeros((2,4))
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
# Random

np.random.random((2,4))

array([[0.43422892, 0.64536021, 0.24013351, 0.79275563],
       [0.27225984, 0.70486571, 0.54646564, 0.76654028]])

In [ ]:
# Linear Space

print(np.linspace(-10,10,10))
print('\n')
print(np.linspace(10,20,5))

[-10.          -7.77777778  -5.55555556  -3.33333333  -1.11111111
   1.11111111   3.33333333   5.55555556   7.77777778  10.        ]


[10.  12.5 15.  17.5 20. ]


In [ ]:
# Identity

print(np.identity(3))
print('\n')
print(np.identity(4))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# **2. Array Attribute**

In [ ]:
a = np.arange(10,dtype=np.int32)          # int64 takes 8 byte default, int32 takes 4 byte
print(a)
print('\n')
b = np.arange(12,dtype=float).reshape(3,4)
print(b)
print('\n')
c = np.arange(16).reshape(2,4,2)
print(c)

[0 1 2 3 4 5 6 7 8 9]


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]]


In [ ]:
# ndim (dimension of an array)

print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
3


In [ ]:
# shape (rows and columns in an array)

print(a.shape)
print(b.shape)
print(c.shape)          # 2- 2D arrays of (4,2)     # (2,4,2)

(10,)
(3, 4)
(2, 4, 2)


In [ ]:
# size (total elements in an array)

print(a.size)
print(b.size)
print(c.size)

10
12
16


In [ ]:
# itemsize (size of item in memory)

print(a.itemsize)
print(b.itemsize)
print(c.itemsize)

8
8
8


In [ ]:
# dtype (tells data type)

print(a.dtype)
print(b.dtype)
print(c.dtype)

int32
float64
int64


# **3. Changing Datatype**

In [ ]:
# astype (to change datatype)     # for saving memory or space

a = np.arange(1,11)
print(a.dtype)
a = a.astype(np.int32)
print(a.dtype)

int64
int32


# **4. Array Operations**

In [ ]:
a = np.arange(12).reshape(3,4)
b = np.arange(12,24).reshape(3,4)

print(a)
print('\n')
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
# scalar operations

# arithmetic

print(a*2)
print('\n')
print(a+2)
print('\n')
print(a-2)
print('\n')
print(a/2)
print('\n')
print(a%2)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


[[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]]


[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]


[[0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]]


In [ ]:
# relational

print(a>5)
print('\n')
print(a<5)
print('\n')
print(a==5)
print('\n')
print(a!=5)

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]


[[ True  True  True  True]
 [ True False False False]
 [False False False False]]


[[False False False False]
 [False  True False False]
 [False False False False]]


[[ True  True  True  True]
 [ True False  True  True]
 [ True  True  True  True]]


In [ ]:
# vector operations

print(a+b)
print('\n')
print(a**b)

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


[[                   0                    1                16384
              14348907]
 [          4294967296         762939453125      101559956668416
     11398895185373143]
 [ 1152921504606846976 -1261475310744950487  1864712049423024128
   6839173302027254275]]


# **5. Array Functions**

In [ ]:
a = np.random.random((3,3))
b = np.round(a*100)
print(b)

[[13. 52. 61.]
 [71. 77. 69.]
 [12. 26. 85.]]


In [ ]:
# max, min, sum, prod

print(np.max(a),'\n')
print(np.min(a),'\n')
print(np.sum(a),'\n')
print(np.prod(a))

0.8471956937497869 

0.11904038977778464 

4.645867593405347 

0.0003954869447122943


In [ ]:
# find the maximum in every row
# 0->col  1->row

print(np.max(b,axis=1))
print(np.max(b,axis=0))

[61. 77. 85.]
[71. 77. 85.]


In [ ]:
# mean, median, std(standard deviation), var(variance)

print(np.mean(b),'\n')
print(np.mean(b,axis=1),'\n')
print(np.median(b),'\n')
print(np.std(b),'\n')
print(np.var(b))

51.77777777777778 

[42.         72.33333333 41.        ] 

61.0 

26.334505365385283 

693.5061728395062


In [ ]:
# trigonometric function

print(np.sin(b))

[[ 0.42016704  0.98662759 -0.96611777]
 [ 0.95105465  0.99952016 -0.11478481]
 [-0.53657292  0.76255845 -0.17607562]]


In [ ]:
# dot product

a2 = np.arange(12).reshape(3,4)
b2 = np.arange(12,24).reshape(4,3)

print(np.dot(a2,b2))

[[114 120 126]
 [378 400 422]
 [642 680 718]]


In [ ]:
# log and exponents

print(np.exp(a2))

[[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03]
 [2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04]]


In [ ]:
# round, flour, cell

print(np.round(np.random.random((2,4))*100),'\n')
print(np.floor(np.random.random((2,4))*100))

[[33. 50. 88. 56.]
 [51. 62. 66. 75.]] 

[[15. 11. 31. 32.]
 [31. 44. 28. 90.]]


# **6. Indexing and Slicing**

In [ ]:
a = np.arange(10)
b = np.arange(12).reshape(4,3)
c = np.arange(8).reshape(2,2,2)

print(a,'\n')
print(b,'\n')
print(c)

[0 1 2 3 4 5 6 7 8 9] 

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
# Indexing

print(a[0],a[-1],a[2],a[-3])
print(b[2][0])
print(b[1][1])
print(c[1][0][1])
print(c[0][1][0])
print(c[0][0][0])
print(c[1][1][0])

0 9 2 7
6
4
5
2
0
6


In [ ]:
# Slicing

print(a[2:5],'\n')
print(a[2:8:2],'\n')
print(a[8:2:-1],'\n')
print(a[8:2:-2])

[2 3 4] 

[2 4 6] 

[8 7 6 5 4 3] 

[8 6 4]


In [ ]:
print(b[0,:],'\n')
print(b[:,2],'\n')
print(b[1:3,1:3],'\n')
print(b[::3,::2],'\n')
print(b[::2,::2],'\n')
print(b[2:3,::2],'\n')
print(b[0:2,1:])

[0 1 2] 

[ 2  5  8 11] 

[[4 5]
 [7 8]] 

[[ 0  2]
 [ 9 11]] 

[[0 2]
 [6 8]] 

[[6 8]] 

[[1 2]
 [4 5]]


In [ ]:
a3 = np.arange(27).reshape(3,3,3)
print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [ ]:
print(a3[1],'\n')
print(a3[::2],'\n')
print(a3[0,1],'\n')
print(a3[1,:,1],'\n')
print(a3[2,1:,1:],'\n')
print(a3[2,0,2:])

[[ 9 10 11]
 [12 13 14]
 [15 16 17]] 

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]] 

[3 4 5] 

[10 13 16] 

[[22 23]
 [25 26]] 

[20]


# **7. Iterating**

In [ ]:
print(a,'\n')
print(b,'\n')
print(c)

[0 1 2 3 4 5 6 7 8 9] 

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
for i in a:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
for i in b:
  print(i)

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]


In [ ]:
for i in c:
  print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [ ]:
for i in np.nditer(b):            # used for iterating single element in n-d arrays
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [ ]:
for i in np.nditer(c):
  print(i)

0
1
2
3
4
5
6
7


# **8. Reshaping**

In [ ]:
# transpose

print(b,'\n')
print(np.transpose(b),'\n')
print(b.T)                           # Short Form

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]] 

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [ ]:
# ravel

print(b,'\n')
print(np.ravel(b))     # convert n-d array to 1-d array

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 

[ 0  1  2  3  4  5  6  7  8  9 10 11]


# **9. Stacking**

In [139]:
# Horizontal Stacking [2*2] [2*2] = [2*(2+2)], [2*4]  (Shape should be same)

a = np.arange(12).reshape(4,3)
b = np.arange(12,24).reshape(4,3)

c = np.hstack((a,b))
print(c,'\n')
c = np.hstack((a,b,a))
print(c)

[[ 0  1  2 12 13 14]
 [ 3  4  5 15 16 17]
 [ 6  7  8 18 19 20]
 [ 9 10 11 21 22 23]] 

[[ 0  1  2 12 13 14  0  1  2]
 [ 3  4  5 15 16 17  3  4  5]
 [ 6  7  8 18 19 20  6  7  8]
 [ 9 10 11 21 22 23  9 10 11]]


In [138]:
# Verticle Stacking [2*2] [2*2] = [(2+2)*2], [4*2]

a = np.arange(12).reshape(4,3)
b = np.arange(12,24).reshape(4,3)

c = np.vstack((a,b))
print(c)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


# **10. Spliting**

In [145]:
# Horizontal Spliting [3*4] = [3*2][3*2]  (Shape should be same)

a = np.arange(12).reshape(3,4)
print(a,'\n')
print(np.hsplit(a,2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [146]:
# Verticle Spliting [3*4] = [1*4][1*4][1*4]  (Shape should be same)

a = np.arange(12).reshape(3,4)
print(a,'\n')
print(np.vsplit(a,3))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
