### **1. Sort Function (np.sort)**
**Return a sorted copy of an array**

In [11]:
import numpy as np

a = np.random.randint(1,100,20)
print(a,'\n')
print(np.sort(a),'\n')
print(np.sort(a)[::-1])             # Descending Order

[56 77 56 22 54 20 13 27 34 70 53 41 27 78  4 39 27 11 34 54] 

[ 4 11 13 20 22 27 27 27 34 34 39 41 53 54 54 56 56 70 77 78] 

[78 77 70 56 56 54 54 53 41 39 34 34 27 27 27 22 20 13 11  4]


In [18]:
b = np.random.randint(1,100,20).reshape(4,5)
print(b,'\n')
print(np.sort(b,axis=0))

[[ 8  6 43 34 44]
 [42 10  9  3 24]
 [64 61 42 65 16]
 [86 84  6 99 54]] 

[[ 8  6  6  3 16]
 [42 10  9 34 24]
 [64 61 42 65 44]
 [86 84 43 99 54]]


### **2. Append Function (np.append)**
**The numpy.append() appends values along the mentioned axis at the end of the array.**

In [13]:
print(a,'\n')
print(np.append(a,102))

[56 77 56 22 54 20 13 27 34 70 53 41 27 78  4 39 27 11 34 54] 

[ 56  77  56  22  54  20  13  27  34  70  53  41  27  78   4  39  27  11
  34  54 102]


In [19]:
print(b,'\n')
print(np.append(b,np.ones((b.shape[0],1)),axis=1))

[[ 8  6 43 34 44]
 [42 10  9  3 24]
 [64 61 42 65 16]
 [86 84  6 99 54]] 

[[ 8.  6. 43. 34. 44.  1.]
 [42. 10.  9.  3. 24.  1.]
 [64. 61. 42. 65. 16.  1.]
 [86. 84.  6. 99. 54.  1.]]


### **3. Concatenate Function (np.append)**
**The numpy.concatenate() function concatenate a sequence of arrays along an existing axis.**

In [23]:
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)

print(a,'\n')
print(b,'\n')
print(np.concatenate((a,b),axis=0))

[[0 1 2]
 [3 4 5]] 

[[ 6  7  8]
 [ 9 10 11]] 

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


### **4. Unique Function (np.unique)**
**We can get the unique values from an array given as a parameter in np.unique() method.**

In [27]:
a = np.array([1,1,2,3,3,4,5,5,5])
b = np.array([[1,2,3,3],[4,5,5,6]])

print(a,'\n')
print(b,'\n')
print(np.unique(a),'\n')
print(np.unique(b))

[1 1 2 3 3 4 5 5 5] 

[[1 2 3 3]
 [4 5 5 6]] 

[1 2 3 4 5] 

[1 2 3 4 5 6]


### **4. Expand Dimension Function (np.expand_dims)**
**Using numpy.expand_dims() method, we can get the expanded dimensions of array**

In [36]:
a = np.arange(12)
print(a,'\n')
print(a.shape,'\n')
print(np.expand_dims(a,axis=0),'\n')
print(np.expand_dims(a,axis=0).shape)
print(np.expand_dims(a,axis=1),'\n')
print(np.expand_dims(a,axis=1).shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11] 

(12,) 

[[ 0  1  2  3  4  5  6  7  8  9 10 11]] 

(1, 12)
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]] 

(12, 1)


### **5. Where Function (np.where)**
**The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied**

In [41]:
a = np.random.randint(10,100,20)
print(a,'\n')
print(np.where(a>50),'\n')
print(a[np.where(a>50)],'\n')
print(np.where(a>50,0,a),'\n')
print(np.where(a%2 == 0,0,a))       # print all even numbers

[35 20 21 49 70 62 24 33 12 52 46 63 85 49 27 90 41 76 46 84] 

(array([ 4,  5,  9, 11, 12, 15, 17, 19]),) 

[70 62 52 63 85 90 76 84] 

[35 20 21 49  0  0 24 33 12  0 46  0  0 49 27  0 41  0 46  0] 

[35  0 21 49  0  0  0 33  0  0  0 63 85 49 27  0 41  0  0  0]


### **6. Argument Max Function (np.argmax)**
**The numpy.argmax() function returns indices of the max element of the array in a particular axis.**

In [46]:
a = np.random.randint(10,100,20)
print(a,'\n')
b = np.random.randint(10,100,20).reshape(5,4)
print(b,'\n')
print(np.argmax(a),'\n')
print(a[np.argmax(a)],'\n')
print(np.argmax(b,axis=1),'\n')
print(a[np.argmax(b,axis=1)],'\n')

[29 40 70 37 54 72 20 19 40 83 49 30 96 96 12 84 92 85 63 46] 

[[29 51 55 89]
 [92 59 28 94]
 [20 14 18 94]
 [80 26 63 51]
 [88 72 98 58]] 

12 

96 

[3 3 3 0 2] 

[37 37 37 29 70] 



### **7. Argument Min Function (np.argmin)**
**The numpy.argmin() function returns indices of the min element of the array in a particular axis.**

In [47]:
a = np.random.randint(10,100,20)
print(a,'\n')
b = np.random.randint(10,100,20).reshape(5,4)
print(b,'\n')
print(np.argmin(a),'\n')
print(a[np.argmin(a)],'\n')
print(np.argmin(b,axis=1),'\n')
print(a[np.argmin(b,axis=1)],'\n')

[46 95 60 32 71 68 16 68 75 38 99 95 58 52 88 69 44 75 49 53] 

[[37 56 34 21]
 [95 17 13 33]
 [25 14 58 54]
 [92 34 91 35]
 [83 59 58 42]] 

6 

16 

[3 2 1 1 3] 

[32 60 95 95 32] 



### **8. Cumulative Sum Function (np.cumsum)**
**The numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.**

In [48]:
a = np.random.randint(10,100,20)
print(a,'\n')
b = np.random.randint(10,100,20).reshape(4,5)
print(b,'\n')

print(np.cumsum(a),'\n')
print(np.cumsum(b),'\n')
print(np.cumsum(b,axis=0),'\n')

[68 59 18 82 18 31 29 15 36 74 66 85 16 91 33 21 76 17 67 39] 

[[23 81 16 79 77]
 [13 91 81 47 75]
 [77 23 99 58 26]
 [49 36 81 98 80]] 

[ 68 127 145 227 245 276 305 320 356 430 496 581 597 688 721 742 818 835
 902 941] 

[  23  104  120  199  276  289  380  461  508  583  660  683  782  840
  866  915  951 1032 1130 1210] 

[[ 23  81  16  79  77]
 [ 36 172  97 126 152]
 [113 195 196 184 178]
 [162 231 277 282 258]] 



### **9. Cumulative Product Function (np.cumprod)**
**The numpy.cumprod() function is used when we want to compute the cumulative product of array elements over a given axis.**

In [49]:
a = np.random.randint(10,100,20)
print(a,'\n')
b = np.random.randint(10,100,20).reshape(4,5)
print(b,'\n')

print(np.cumprod(a),'\n')
print(np.cumprod(b),'\n')
print(np.cumprod(b,axis=0),'\n')

[26 72 59 92 51 99 39 62 37 61 28 53 42 56 52 32 49 54 64 91] 

[[23 66 33 51 99]
 [17 47 20 71 72]
 [39 59 24 27 67]
 [24 78 44 13 79]] 

[                  26                 1872               110448
             10161216            518222016          51303979584
        2000855203776      124053022634112     4589961837462144
   279987672085190784  7839654818385341952 -8773408320896563712
   451731996535356416  6850247732270407680  5724744677579718656
 -1275611054544519168 -7164709451552784384   487315164050227200
 -5705317648204562432 -2675071922747736064] 

[                  23                 1518                50094
              2554794            252924606           4299718302
         202086760194        4041735203880      286963199475480
    20661350362234560   805792664127147840 -7798465037626932288
 -2695720165950858752  1002531814165020160 -6617344745781855744
  7204422764621426688  8542653429184733184  6941869409937227776
 -1989418039363796992  8856671553646002176] 

[

### **10. Percentile Function (np.cumprod)**
**numpy.percentile() function used to compute the nth percentile of the given data(array elements) along the specified data.**

In [53]:
a = np.random.randint(10,100,20)
print(a,'\n')
b = np.random.randint(10,100,20).reshape(4,5)
print(b,'\n')

print(np.percentile(a,100),'\n')
print(np.percentile(a,50),'\n')
print(np.median(a),'\n')            # To check
print(np.percentile(a,0),'\n')
print(np.cumprod(b,axis=0),'\n')

[34 18 89 67 16 92 68 57 66 18 57 29 87 13 63 56 82 78 79 26] 

[[48 29 79 28 34]
 [83 96 54 64 91]
 [32 91 99 73 14]
 [33 95 45 31 87]] 

92.0 

60.0 

60.0 

13.0 

[[      48       29       79       28       34]
 [    3984     2784     4266     1792     3094]
 [  127488   253344   422334   130816    43316]
 [ 4207104 24067680 19005030  4055296  3768492]] 



### **10. Histogram Function (np.histogram)**
**Numpy has a built in numpy.histogram() function which represents the frequency of data distribution in the graphical form.**

In [54]:
a = np.random.randint(0,50,8)
print(a,'\n')

print(np.histogram(a,bins=[10,20,30,40,50]),'\n')

[22 11 30 29 19 41 48  1] 

[[48 90 99 78 17]
 [45 83 30 36 14]
 [97 50 25 77 23]
 [86 48 22 67 97]] 

(array([2, 2, 1, 2]), array([10, 20, 30, 40, 50])) 



### **11. Correlation Coefficient Function (np.corrcoef)**
**Numpy has a built in numpy.corrcoef() function which returns Pearson product-moment correlation coefficients.**

In [55]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

print(np.corrcoef(salary,experience))

[[1.         0.25344572]
 [0.25344572 1.        ]]


### **12. Isin Function (np.isin)**
**Using numpy.isin() method, we can check or see that one array having values are checked in a different numpy array having different elements with different sizes.**

In [58]:
a = np.arange(10,20)
b = np.arange(13,16)
print(a,'\n')
print(np.isin(a,b),'\n')
print(a[np.isin(a,b)])

[10 11 12 13 14 15 16 17 18 19] 

[False False False  True  True  True False False False False] 

[13 14 15]


### **12. Flip Function (np.flip)**
**The numpy.flip() function reverses the order of array elements along the specified axis, preventing the shape of the array.**

In [64]:
print(a,'\n')
print(np.flip(a),'\n')
b = np.random.randint(10,100,20).reshape(4,5)
print(b,'\n')
print(np.flip(b,axis=0),'\n')
print(np.flip(b,axis=1))

[10 11 12 13 14 15 16 17 18 19] 

[19 18 17 16 15 14 13 12 11 10] 

[[16 42 36 26 19]
 [52 70 18 77 14]
 [92 33 69 60 49]
 [92 76 43 93 65]] 

[[92 76 43 93 65]
 [92 33 69 60 49]
 [52 70 18 77 14]
 [16 42 36 26 19]] 

[[19 26 36 42 16]
 [14 77 18 70 52]
 [49 60 69 33 92]
 [65 93 43 76 92]]


### **13. Put Function(np.put)**
**The numpy.put() function replaces specific elements of an array with given values of parr. Array indexed works on flattened array.**

In [66]:
a = np.array([11,53,28,50,38,37,94,5,30,68,9])
print(a,'\n')
np.put(a,[0,1],[110,530])         # Permanent Changes
print(a,)

[11 53 28 50 38 37 94  5 30 68  9] 

[110 530  28  50  38  37  94   5  30  68   9]


### **14. Delete Function(np.delete)**
**The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.**

In [69]:
print(a,'\n')
print(np.delete(a,[1,10]))

[110 530  28  50  38  37  94   5  30  68   9] 

[110  28  50  38  37  94   5  30  68]


### **15. Set Functions**
*  np.union1d
*  np.intersect1d
*  np.setdiff1d
*  np.setxor1d
*  np.in1d

In [70]:
# np.union1d

a = np.arange(1,7)
b = np.arange(4,9)
print(a,'\n')
print(b,'\n')
print(np.union1d(a,b))

[1 2 3 4 5 6] 

[4 5 6 7 8] 

[1 2 3 4 5 6 7 8]


In [71]:
# np.intersect1d

print(a,'\n')
print(b,'\n')
print(np.intersect1d(a,b))

[1 2 3 4 5 6] 

[4 5 6 7 8] 

[4 5 6]


In [73]:
# np.setdiff1d

print(a,'\n')
print(b,'\n')
print(np.setdiff1d(a,b),'\n')            # In a but not in b
print(np.setdiff1d(b,a))

[1 2 3 4 5 6] 

[4 5 6 7 8] 

[1 2 3] 

[7 8]


In [74]:
# np.setxor1d

print(a,'\n')
print(b,'\n')
print(np.setxor1d(a,b))                 # Not Common from a and b

[1 2 3 4 5 6] 

[4 5 6 7 8] 

[1 2 3 7 8]


In [80]:
# np.in1d

print(a,'\n')
print(b,'\n')
print(np.in1d(a,b),'\n')
print(a[np.in1d(a,b)],'\n')
print(np.in1d(b,a),'\n')
print(b[np.in1d(b,a)])

[1 2 3 4 5 6] 

[4 5 6 7 8] 

[False False False  True  True  True] 

[4 5 6] 

[ True  True  True False False] 

[4 5 6]


### **16. Clip Function (np.clip)**
**numpy.clip() function is used to Clip (limit) the values in an array.**

In [82]:
a = np.array([11,53,28,50,38,37,94,5,30,68,9])
print(a,'\n')
print(np.clip(a,a_min=30,a_max=60))

[11 53 28 50 38 37 94  5 30 68  9] 

[30 53 30 50 38 37 60 30 30 60 30]
